services:
  - type: web
    name: orbit-manager-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_ID
        sync: false
      - key: DEV_IDS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0